const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');
const multer = require('multer');
const path = require('path');

const Member = require('./models/Member');

const app = express();

app.use(cors({
    origin: 'http://localhost:3000', // Allow the React frontend to connect
    methods: ['GET', 'POST', 'PUT', 'DELETE'],
    credentials: true
}));
app.use(express.json());

app.use('/uploads', express.static(path.join(__dirname, 'uploads')));

mongoose.connect('mongodb://127.0.0.1:27017/team_db')
    .then(() => console.log("MongoDB Connected Successfully"))
    .catch(err => console.log("MongoDB Connection Error:", err));

// Set up Multer for Image Uploads
const storage = multer.diskStorage({
    destination: function(req, file, cb) {
        cb(null, 'uploads/'); // Saves files to the uploads folder
    },
    filename: function(req, file, cb) {
        // Appends a timestamp to prevent file name collisions
        cb(null, Date.now() + '-' + file.originalname);
    }
});
const upload = multer({ storage: storage });

// API ENDPOINTS`
// 1. Add New Member (POST)
app.post('/members', upload.single('image'), async (req, res) => {
    try {
        const newMemberData = {
            ...req.body,
            image: req.file ? req.file.path : null // Save the path generated by multer
        };
        const newMember = new Member(newMemberData);
        await newMember.save();
        res.status(201).json({ message: "Member added successfully", member: newMember });
    } catch (error) {
        res.status(500).json({ message: "Error saving member", error });
    }
});

// 2. Get All Members (GET)
app.get('/members', async (req, res) => {
    try {
        const members = await Member.find();
        res.status(200).json(members);
    } catch (error) {
        res.status(500).json({ message: "Error fetching members", error });
    }
});

// 3. Get Single Member by ID (GET)
app.get('/members/:id', async (req, res) => {
    try {
        const member = await Member.findById(req.params.id);
        if (!member) return res.status(404).json({ message: "Member not found" });
        res.status(200).json(member);
    } catch (error) {
        res.status(500).json({ message: "Error fetching member details", error });
    }
});

// Start the server
const PORT = 5023;
app.listen(PORT, () => {
    console.log(`Server is running on http://localhost:${PORT}`);
});